# Generated by Django 5.1 on 2024-08-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Sale', 'Sale')], max_length=30),
        ),
    ]
